# Generated by Django 5.0.1 on 2024-07-19 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_customuser_name_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.CharField(max_length=255)),
                ('qrCode', models.CharField(max_length=255)),
                ('certificateExpirationDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('eventSubheading', models.CharField(max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eventCertificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.certificate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.organization')),
                ('eventDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.eventdetail')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='eventCertificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='apis.event'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30, null=True)),
                ('middleName', models.CharField(max_length=255, null=True)),
                ('middleInitial', models.CharField(max_length=3, null=True)),
                ('fullName', models.CharField(max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.event')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.participant'),
        ),
    ]
