# Generated by Django 5.0.1 on 2024-07-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_certificate_eventdetail_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personUserId',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
