# Generated by Django 5.0.1 on 2024-07-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_customuser_personuserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='personUserId',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
